openapi: 3.0.0
info:
  title: Polysplit RPC
  version: "1.0"
paths:
  /status:
    get:
      operationId: GetStatus
      responses:
        "200":
          description: GET /status Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - success
                  data:
                    type: object
                    properties:
                      status:
                        type: string
                    required:
                      - status
                    example:
                      status: healthy
                required:
                  - status
                  - data
              examples:
                example1:
                  value:
                    status: success
                    data:
                      status: healthy
        "400":
          description: GET /status Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - error
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                    required:
                      - message
                required:
                  - status
                  - error
              examples:
                example1:
                  value:
                    status: error
                    error:
                      message: Sample error message
      summary: Status of server
      tags:
        - Status
  /v1/stats:
    get:
      operationId: GetV1Stats
      responses:
        "200":
          description: GET /v1/stats Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - success
                  data:
                    type: object
                    properties:
                      shared:
                        type: object
                        properties:
                          countFromLanding:
                            type: number
                            format: double
                            minimum: 5e-324
                            exclusiveMinimum: false
                            maximum: 1.7976931348623157e+308
                            exclusiveMaximum: false
                          countFromLanding24:
                            type: number
                            format: double
                            minimum: 5e-324
                            exclusiveMinimum: false
                            maximum: 1.7976931348623157e+308
                            exclusiveMaximum: false
                        required:
                          - countFromLanding
                          - countFromLanding24
                      perChainId:
                        type: object
                        additionalProperties:
                          type: object
                          properties:
                            popularRpc:
                              type: string
                            uniqueUsers:
                              type: number
                              format: double
                              minimum: 5e-324
                              exclusiveMinimum: false
                              maximum: 1.7976931348623157e+308
                              exclusiveMaximum: false
                            responseTimeMs:
                              type: object
                              properties:
                                avg:
                                  type: number
                                  format: double
                                  minimum: 5e-324
                                  exclusiveMinimum: false
                                  maximum: 1.7976931348623157e+308
                                  exclusiveMaximum: false
                                min:
                                  type: number
                                  format: double
                                  minimum: 5e-324
                                  exclusiveMinimum: false
                                  maximum: 1.7976931348623157e+308
                                  exclusiveMaximum: false
                                max:
                                  type: number
                                  format: double
                                  minimum: 5e-324
                                  exclusiveMinimum: false
                                  maximum: 1.7976931348623157e+308
                                  exclusiveMaximum: false
                              required:
                                - avg
                                - min
                                - max
                            topRpcs:
                              type: array
                              items:
                                type: string
                            errorCount:
                              type: number
                              format: double
                              minimum: 5e-324
                              exclusiveMinimum: false
                              maximum: 1.7976931348623157e+308
                              exclusiveMaximum: false
                            errorCount24:
                              type: number
                              format: double
                              minimum: 5e-324
                              exclusiveMinimum: false
                              maximum: 1.7976931348623157e+308
                              exclusiveMaximum: false
                            okCount:
                              type: number
                              format: double
                              minimum: 5e-324
                              exclusiveMinimum: false
                              maximum: 1.7976931348623157e+308
                              exclusiveMaximum: false
                            okCount24:
                              type: number
                              format: double
                              minimum: 5e-324
                              exclusiveMinimum: false
                              maximum: 1.7976931348623157e+308
                              exclusiveMaximum: false
                            totalCount:
                              type: number
                              format: double
                              minimum: 5e-324
                              exclusiveMinimum: false
                              maximum: 1.7976931348623157e+308
                              exclusiveMaximum: false
                            totalCount24:
                              type: number
                              format: double
                              minimum: 5e-324
                              exclusiveMinimum: false
                              maximum: 1.7976931348623157e+308
                              exclusiveMaximum: false
                            avgAttempts:
                              type: number
                              format: double
                              minimum: 5e-324
                              exclusiveMinimum: false
                              maximum: 1.7976931348623157e+308
                              exclusiveMaximum: false
                            avgAttempts24:
                              type: number
                              format: double
                              minimum: 5e-324
                              exclusiveMinimum: false
                              maximum: 1.7976931348623157e+308
                              exclusiveMaximum: false
                          required:
                            - popularRpc
                            - uniqueUsers
                            - responseTimeMs
                            - topRpcs
                            - errorCount
                            - errorCount24
                            - okCount
                            - okCount24
                            - totalCount
                            - totalCount24
                            - avgAttempts
                            - avgAttempts24
                    required:
                      - shared
                      - perChainId
                required:
                  - status
                  - data
        "400":
          description: GET /v1/stats Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - error
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                    required:
                      - message
                required:
                  - status
                  - error
              examples:
                example1:
                  value:
                    status: error
                    error:
                      message: Sample error message
components:
  schemas: {}
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes: {}
  links: {}
  callbacks: {}
tags: []
servers:
  - url: https://rpc.polysplit.cloud
