openapi: 3.0.0
info:
  title: Polysplit RPC
  version: "1.0"
paths:
  /status:
    get:
      operationId: GetStatus
      responses:
        "200":
          description: GET /status Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetStatusSuccessfulResponse"
              examples:
                example1:
                  value:
                    status: success
                    data:
                      status: healthy
        "400":
          description: GET /status Error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetStatusErrorResponse"
              examples:
                example1:
                  value:
                    status: error
                    error:
                      message: Sample error message
      summary: Status of server
      tags:
        - Status
  /v1/stats:
    get:
      operationId: GetV1Stats
      responses:
        "200":
          description: GET /v1/stats Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetV1StatsSuccessfulResponse"
        "400":
          description: GET /v1/stats Error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetV1StatsErrorResponse"
              examples:
                example1:
                  value:
                    status: error
                    error:
                      message: Sample error message
components:
  schemas:
    GetStatusSuccessfulResponse:
      type: object
      properties:
        status:
          type: string
          enum:
            - success
        data:
          type: object
          properties:
            status:
              type: string
          required:
            - status
          example:
            status: healthy
      required:
        - status
        - data
    GetStatusErrorResponse:
      type: object
      properties:
        status:
          type: string
          enum:
            - error
        error:
          type: object
          properties:
            message:
              type: string
          required:
            - message
      required:
        - status
        - error
    GetV1StatsSuccessfulResponse:
      type: object
      properties:
        status:
          type: string
          enum:
            - success
        data:
          type: object
          properties:
            shared:
              type: object
              properties:
                countFromLanding:
                  type: integer
                  format: int64
                  minimum: -9007199254740991
                  exclusiveMinimum: false
                  maximum: 9007199254740991
                  exclusiveMaximum: false
                countFromLanding24:
                  type: integer
                  format: int64
                  minimum: -9007199254740991
                  exclusiveMinimum: false
                  maximum: 9007199254740991
                  exclusiveMaximum: false
              required:
                - countFromLanding
                - countFromLanding24
            perChainId:
              type: object
              additionalProperties:
                type: object
                properties:
                  popularRpc:
                    type: string
                  uniqueUsers:
                    type: integer
                    format: int64
                    minimum: -9007199254740991
                    exclusiveMinimum: false
                    maximum: 9007199254740991
                    exclusiveMaximum: false
                  responseTimeMs:
                    type: object
                    properties:
                      avg:
                        type: integer
                        format: int64
                        minimum: -9007199254740991
                        exclusiveMinimum: false
                        maximum: 9007199254740991
                        exclusiveMaximum: false
                      min:
                        type: integer
                        format: int64
                        minimum: -9007199254740991
                        exclusiveMinimum: false
                        maximum: 9007199254740991
                        exclusiveMaximum: false
                      max:
                        type: integer
                        format: int64
                        minimum: -9007199254740991
                        exclusiveMinimum: false
                        maximum: 9007199254740991
                        exclusiveMaximum: false
                    required:
                      - avg
                      - min
                      - max
                  topRpcs:
                    type: array
                    items:
                      type: string
                  errorCount:
                    type: integer
                    format: int64
                    minimum: -9007199254740991
                    exclusiveMinimum: false
                    maximum: 9007199254740991
                    exclusiveMaximum: false
                  errorCount24:
                    type: integer
                    format: int64
                    minimum: -9007199254740991
                    exclusiveMinimum: false
                    maximum: 9007199254740991
                    exclusiveMaximum: false
                  okCount:
                    type: integer
                    format: int64
                    minimum: -9007199254740991
                    exclusiveMinimum: false
                    maximum: 9007199254740991
                    exclusiveMaximum: false
                  okCount24:
                    type: integer
                    format: int64
                    minimum: -9007199254740991
                    exclusiveMinimum: false
                    maximum: 9007199254740991
                    exclusiveMaximum: false
                  totalCount:
                    type: integer
                    format: int64
                    minimum: -9007199254740991
                    exclusiveMinimum: false
                    maximum: 9007199254740991
                    exclusiveMaximum: false
                  totalCount24:
                    type: integer
                    format: int64
                    minimum: -9007199254740991
                    exclusiveMinimum: false
                    maximum: 9007199254740991
                    exclusiveMaximum: false
                  avgAttempts:
                    type: integer
                    format: int64
                    minimum: -9007199254740991
                    exclusiveMinimum: false
                    maximum: 9007199254740991
                    exclusiveMaximum: false
                  avgAttempts24:
                    type: integer
                    format: int64
                    minimum: -9007199254740991
                    exclusiveMinimum: false
                    maximum: 9007199254740991
                    exclusiveMaximum: false
                required:
                  - popularRpc
                  - uniqueUsers
                  - responseTimeMs
                  - topRpcs
                  - errorCount
                  - errorCount24
                  - okCount
                  - okCount24
                  - totalCount
                  - totalCount24
                  - avgAttempts
                  - avgAttempts24
          required:
            - shared
            - perChainId
      required:
        - status
        - data
    GetV1StatsErrorResponse:
      type: object
      properties:
        status:
          type: string
          enum:
            - error
        error:
          type: object
          properties:
            message:
              type: string
          required:
            - message
      required:
        - status
        - error
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes: {}
  links: {}
  callbacks: {}
tags: []
servers:
  - url: https://rpc.polysplit.cloud
