openapi: 3.0.0
info:
  title: Gotbit Service Chacker API
  version: "1.0"
paths:
  /api/health:
    get:
      operationId: GetApiHealth
      responses:
        "200":
          description: GET /api/health Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - success
                  data:
                    type: object
                    properties:
                      status:
                        type: string
                    required:
                      - status
                    example:
                      status: healthy
                required:
                  - status
                  - data
              examples:
                example1:
                  value:
                    status: success
                    data:
                      status: healthy
        "400":
          description: GET /api/health Error response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - error
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                    required:
                      - message
                required:
                  - status
                  - error
              examples:
                example1:
                  value:
                    status: error
                    error:
                      message: Sample error message
      summary: Status of server
      tags:
        - Default
components:
  schemas: {}
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes: {}
  links: {}
  callbacks: {}
tags: []
servers:
  - url: http://localhost:3001
